#####It is my second example of dockerfile######
####using copy command
######START#####


From alpine 
RUN apk add tree
RUN apk add curl
RUN apk add nano
RUN mkdir project
#####creating a directory and copy the files into that .#####

COPY ./ ./project

#########END

