#####It is my second example of dockerfile######
####using copy command
######START#####


RUN From redis
RUN yum install tree
RUN yum install nano
RUN mkdir project
#####creating a directory and copy the files into that .#####

COPY ./ ./project

#########END

